version: '3.8'

services:
  temperature-api:
    build:
      context: ./apps/temperature-api
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
    networks:
      - warmhouse-net

  smart_home_db:
    image: postgres:15
    environment:
      POSTGRES_DB: smart_home
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - ./smart_home/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - warmhouse-net

networks:
  warmhouse-net:
    driver: bridge